//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_mobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class favourite
    {
        public int id { get; set; }
        public Nullable<int> id_word { get; set; }
        public Nullable<int> id_user { get; set; }
    
        public virtual login login { get; set; }
    }
}
